In [1]:
import pandas as pd
import numpy as np

In [2]:
dataset = pd.read_csv("engineering_colleges.csv")

<ipython-input-2-199c8b20c541>:1: DtypeWarning: Columns (15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218) have mixed types. Specify dtype option on import or set low_memory=False.
  dataset = pd.read_csv("engineering_colleges.csv")


In [3]:
dataset.head()

College Name Genders Accepted  \
0         National Institute of Technology Rourkela             Co-Ed   
1  Visvesvaraya National Institute of Technology ...            Co-Ed   
2             Netaji Subhas University of Technology            Co-Ed   
3                      Birla Institute of Technology            Co-Ed   
4  International Institute of Information Technology            Co-Ed   

  Campus Size Total Student Enrollments Total Faculty Established Year Rating  \
0   647 Acres                      4811           329             2007   3.12   
1   215 Acres                      1071           192             2007    NaN   
2   145 Acres                      3759           101             2018    NaN   
3   980 Acres                      4506           284             1955    NaN   
4    66 Acres                      1721            85             2001   3.05   

  University                                            Courses  \
0        NaN  B.Tech Mechanical Engineering, B.Tech Computer...   
1        NaN  B.Tech Computer Science Engineering, B.Tech El...   
2        NaN  B.Tech Computer Engineering, B.Tech Electronic...   
3        NaN  B.Tech Computer Science Engineering, B.Tech El...   
4        NaN  B.Tech Computer Science and Engineering, M.Tec...   

                                          Facilities  ... Unnamed: 210  \
0  Boys Hostel, Girls Hostel, Gym, Library, Sport...  ...          NaN   
1  Boys Hostel, Girls Hostel, Gym, Library, Sport...  ...          NaN   
2  Boys Hostel, Girls Hostel, Gym, Library, Sport...  ...          NaN   
3  Boys Hostel, Girls Hostel, Gym, Library, Sport...  ...          NaN   
4  Boys Hostel, Girls Hostel, Gym, Library, Sport...  ...          NaN   

  Unnamed: 211 Unnamed: 212 Unnamed: 213 Unnamed: 214 Unnamed: 215  \
0          NaN          NaN          NaN          NaN          NaN   
1          NaN          NaN          NaN          NaN          NaN   
2          NaN          NaN          NaN          NaN          NaN   
3          NaN          NaN          NaN          NaN          NaN   
4          NaN          NaN          NaN          NaN          NaN   

  Unnamed: 216 Unnamed: 217 Unnamed: 218 Unnamed: 219  
0          NaN          NaN          NaN          NaN  
1          NaN          NaN          NaN          NaN  
2          NaN          NaN          NaN          NaN  
3          NaN          NaN          NaN          NaN  
4          NaN          NaN          NaN          NaN  

[5 rows x 220 columns]

In [4]:
dataset["overview"] = np.nan
dataset.head()

College Name Genders Accepted  \
0         National Institute of Technology Rourkela             Co-Ed   
1  Visvesvaraya National Institute of Technology ...            Co-Ed   
2             Netaji Subhas University of Technology            Co-Ed   
3                      Birla Institute of Technology            Co-Ed   
4  International Institute of Information Technology            Co-Ed   

  Campus Size Total Student Enrollments Total Faculty Established Year Rating  \
0   647 Acres                      4811           329             2007   3.12   
1   215 Acres                      1071           192             2007    NaN   
2   145 Acres                      3759           101             2018    NaN   
3   980 Acres                      4506           284             1955    NaN   
4    66 Acres                      1721            85             2001   3.05   

  University                                            Courses  \
0        NaN  B.Tech Mechanical Engineering, B.Tech Computer...   
1        NaN  B.Tech Computer Science Engineering, B.Tech El...   
2        NaN  B.Tech Computer Engineering, B.Tech Electronic...   
3        NaN  B.Tech Computer Science Engineering, B.Tech El...   
4        NaN  B.Tech Computer Science and Engineering, M.Tec...   

                                          Facilities  ... Unnamed: 211  \
0  Boys Hostel, Girls Hostel, Gym, Library, Sport...  ...          NaN   
1  Boys Hostel, Girls Hostel, Gym, Library, Sport...  ...          NaN   
2  Boys Hostel, Girls Hostel, Gym, Library, Sport...  ...          NaN   
3  Boys Hostel, Girls Hostel, Gym, Library, Sport...  ...          NaN   
4  Boys Hostel, Girls Hostel, Gym, Library, Sport...  ...          NaN   

  Unnamed: 212 Unnamed: 213 Unnamed: 214 Unnamed: 215 Unnamed: 216  \
0          NaN          NaN          NaN          NaN          NaN   
1          NaN          NaN          NaN          NaN          NaN   
2          NaN          NaN          NaN          NaN          NaN   
3          NaN          NaN          NaN          NaN          NaN   
4          NaN          NaN          NaN          NaN          NaN   

  Unnamed: 217 Unnamed: 218 Unnamed: 219 overview  
0          NaN          NaN          NaN      NaN  
1          NaN          NaN          NaN      NaN  
2          NaN          NaN          NaN      NaN  
3          NaN          NaN          NaN      NaN  
4          NaN          NaN          NaN      NaN  

[5 rows x 221 columns]

In [19]:

for i in dataset.index:
#     dataset['overview'][i] = dataset.iloc['Campus Size[i]', 'Courses[i]', 'Facilities[i]', 'City[i]', 'State[i]', 'College Type[i]', 'Average Fees[i]'].to_string(header=False, index=False)

    temp = str(dataset['Campus Size'][i]) + str(dataset['City'][i]) + str(dataset['State'][i])  + str(dataset['Average Fees'][i])
    dataset['overview'][i] = temp

<ipython-input-19-2834156b9e26>:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset['overview'][i] = temp


In [20]:
dataset.head(3)

College Name Genders Accepted  \
0         National Institute of Technology Rourkela             Co-Ed   
1  Visvesvaraya National Institute of Technology ...            Co-Ed   
2             Netaji Subhas University of Technology            Co-Ed   

  Campus Size Total Student Enrollments Total Faculty Established Year Rating  \
0   647 Acres                      4811           329             2007   3.12   
1   215 Acres                      1071           192             2007    NaN   
2   145 Acres                      3759           101             2018    NaN   

  University                                            Courses  \
0        NaN  B.Tech Mechanical Engineering, B.Tech Computer...   
1        NaN  B.Tech Computer Science Engineering, B.Tech El...   
2        NaN  B.Tech Computer Engineering, B.Tech Electronic...   

                                          Facilities  ... Unnamed: 211  \
0  Boys Hostel, Girls Hostel, Gym, Library, Sport...  ...          NaN   
1  Boys Hostel, Girls Hostel, Gym, Library, Sport...  ...          NaN   
2  Boys Hostel, Girls Hostel, Gym, Library, Sport...  ...          NaN   

  Unnamed: 212 Unnamed: 213 Unnamed: 214 Unnamed: 215 Unnamed: 216  \
0          NaN          NaN          NaN          NaN          NaN   
1          NaN          NaN          NaN          NaN          NaN   
2          NaN          NaN          NaN          NaN          NaN   

  Unnamed: 217 Unnamed: 218 Unnamed: 219  \
0          NaN          NaN          NaN   
1          NaN          NaN          NaN   
2          NaN          NaN          NaN   

                                overview  
0          647 AcresRourkelaOdisha350600  
1  215 AcresNagpurMaharashtra273596.6667  
2          145 AcresNew DelhiDelhi352320  

[3 rows x 221 columns]

In [21]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [22]:
tfidf = TfidfVectorizer(stop_words="english")
dataset['overview'] = dataset['overview'].fillna("")
tfidf_matrix = tfidf.fit_transform(dataset['overview'])



In [23]:
from sklearn.metrics.pairwise import linear_kernel

In [24]:
cosine_sim = linear_kernel(tfidf_matrix, tfidf_matrix)
print(cosine_sim)

[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


In [25]:
indices_clg = pd.Series(dataset.index, dataset['College Name']).drop_duplicates()
indices_overview = pd.Series(dataset.index, dataset['overview']).drop_duplicates()
print(indices_overview[indices_clg['Netaji Subhas University of Technology']])

print(dataset['overview'][2])

2
145 AcresNew DelhiDelhi352320


In [29]:
def get_recommendation(preferences, cosine_sim = cosine_sim):
    ind = indices_overview[preferences]
    sim_scores = enumerate(cosine_sim[ind])
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
    sim_scores = sim_scores[1:6]

    sim_index = [i[0] for i in sim_scores]
    print(dataset["College Name"].iloc[sim_index])
    print(dataset["City"].iloc[sim_index])


get_recommendation("145 AcresNew DelhiDelhi352320")

242     Maharaja Surajmal Institute of Technology
414              Ambedkar Institute of Technology
503     Bhagwan Parshuram Institute of Technology
640    HMR Institute of Technology and Management
690               TERI School of Advanced Studies
Name: College Name, dtype: object
242    New Delhi
414    New Delhi
503    New Delhi
640    New Delhi
690    New Delhi
Name: City, dtype: object
